export interface FormItem {
  name: string;
}
export interface SubmissionItem {
  id: string;
  formName: string;
  data: Record<string, any>;
  schemaHash: string;
  status: 'pending' | 'submitted' | 'failed';
  is_submittable: number;
}
export type RawField = {
  fieldname: string;
  fieldtype: string;
  label: string;
  options?: string;
  default?: string;
  hidden?: number;
  print_hide?: number;
  report_hide?: number;
  depends_on?: string;
  reqd:number;
};
export interface DocType {
  data: Data;
  fields: Field[];
  permissions: Permission[];
  actions: [];
  links: [];
}
export interface Data {
  name: string;
  creation: string;
  modified: string;
  modified_by: string;
  owner: string;
  docStatus: number;
  idx: number;
  issingle: number;
  istable: number;
  editable_grid: number;
  track_changes: number;
  module: string;
  autoname: number;
  name_case: string;
  sort_field: string;
  sort_order: string;
  readonly: number;
  in_create: number;
  allow_copy: number;
  allow_rename: number;
  allow_import: number;
  hide_toolbar: number;
  track_seen: number;
  max_attachments: number;
  document_type: string;
  engine: string;
  is_submittable: number;
  show_name_in_global_search: number;
  custom: number;
  beta: number;
  has_web_view: number;
  allow_guest_to_view: number;
  qick_entry: number;
  is_tree: number;
  track_views: number;
  all_events_in_timeline: number;
  allow_auto_repeat: number;
  show_preview_popup: number;
  email_append_to: number;
  index_web_pages_for_search: number;
  docType: string;
}
export interface Field {
  name: string;
  creation: string;
  modified: string;
  modified_by: string;
  owner: string;
  docStatus: number;
  parent: string;
  parentfield: string;
  parenttype: string;
  idx: number;
  fieldname: string;
  label: string;
  fieldtype: string;
  options: string;
  search_index: number;
  hidden: number;
  set_only_once: number;
  print_hide: number;
  report_hide: number;
  reqd: number;
  bold: number;
  in_global_search: number;
  collapsible: number;
  unique: number;
  no_copy: number;
  allow_on_submit: number;
  permlevel: number;
  ignore_user_permissions: number;
  columns: number;
  in_list_view: number;
  in_standard_filter: number;
  read_only: number;
  precision: number;
  length: number;
  ignore_xss_filter: number;
  in_filter: number;
  print_hide_if_no_value: number;
  allow_bulk_edit: number;
  remember_last_selected_value: number;
  hide_days: number;
  hide_seconds: number;
  in_preview: number;
  allow_in_quick_entry: number;
  translatable: number;
  fetch_if_empty: number;
  hide_border: number;
  non_negative: number;
  docType: string;
  depends_on?: string;
}
export interface Permission {
  name: string;
  creation: string;
  modified: string;
  modified_by: string;
  owner: string;
  docStatus: number;
  parent: string;
  parentfield: string;
  parenttype: string;
  idx: number;
  permlevel: number;
  role: string;
  read: number;
  write: number;
  create: number;
  submit: number;
  cancel: number;
  delete: number;
  amend: number;
  report: number;
  export: number;
  import: number;
  share: number;
  print: number;
  email: number;
  set_user_permissions: number;
  if_owner: number;
  docType: string;
}
